name: New Game

on:
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight UTC
  workflow_dispatch:  # Manual trigger

permissions:
  contents: write

jobs:
  new-game:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: czl9707/gh-space-shooter@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          output-path: 'profile/game.gif'
          strategy: 'random'
