# Visit https://github.com/lowlighter/metrics#-documentation for full reference

# Your GitHub token
# The following scopes are required:
#  - public_access (default scope)
# The following additional scopes may be required:
#  - read:org      (for organization related metrics)
#  - read:user     (for user related data)
#  - read:packages (for some packages related data)
#  - repo          (optional, if you want to include private repositories)

name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Manual execution
  workflow_dispatch: {}
  # Run on push to the default branch as well as historical names
  push:
    branches: ["Jed"]
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics/profile.svg

          # Options
          template: classic
          base: header, activity, community, repositories
          config_timezone: Asia/Manila

          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 20
          plugin_languages_other: yes
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%

          repositories_forks: yes


      - name: WakaTime
        uses: lowlighter/metrics@latest
        with:
          token: NOT_NEEDED
          filename: metrics/wakatime.svg

          # Options
          config_timezone: Asia/Manila
          plugin_wakatime: yes
          plugin_wakatime_days: 365
          plugin_wakatime_limit: 5
          plugin_wakatime_repositories_visibility: all
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          plugin_wakatime_url: https://wakatime.com/@Jed556
          plugin_wakatime_user: current

      - name: Anilist
        uses: lowlighter/metrics@latest
        with:
          token: NOT_NEEDED
          filename: metrics/anilist.svg

          # Options
          config_timezone: Asia/Manila
          plugin_anilist: yes
          plugin_anilist_limit: 2
          plugin_anilist_limit_characters: 22
          plugin_anilist_medias: anime, manga
          plugin_anilist_sections: favorites
          plugin_anilist_shuffle: yes
          plugin_anilist_user: Jed556
